version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - melekes
  - tessr
  ignore:
  - dependency-name: github.com/golang/protobuf
    versions:
    - 1.4.3
    - 1.5.1
