run:
  deadline: 1m

linters:
  enable-all: true
  disable:
    - gocyclo
    - golint
    - gosimple
    - deadcode
    - structcheck
    - maligned
    - errcheck
    - dupl
    - ineffassign
    - interfacer
    - unconvert
    - goconst
    - unparam
    - nakedret
    - lll
    - gochecknoglobals
    - gochecknoinits
    - scopelint
    - stylecheck
