linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    # - funlen
    # - gochecknoglobals
    # - gochecknoinits
    - goconst
    - gocritic
    # - gocyclo
    # - godox
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    # - maligned
    - nakedret
    - prealloc
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    # - unparam
    - unused
    - varcheck
    # - whitespace
    # - wsl
    # - gocognit

issues:
  exclude-rules:
    - linters:
        - lll
      source: "https://"

linters-settings:
  dogsled:
    max-blank-identifiers: 3
  govet:
    check-shadowing: true
