version: 2.1

executors:
  golang:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/tendermint/go-amino
    environment:
      GOBIN: /tmp/bin

jobs:
  test_cover:
    executor: golang
    steps:
      - checkout
      - run:
          name: "Run tests"
          command: |
            make test

workflows:
  version: 2
  test-suite:
    jobs:
      - test_cover
