version: 2.1

executors:
  golang:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/tendermint/go-amino
    environment:
      GOBIN: /tmp/bin
  release: true

jobs:
  test_cover:
    executor: golang
    steps:
      - run:
          name: "Run tests"
          command: |
          make test
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  fuzz_test_Binary:
    executor: golang
    steps:
      - run:
          name: "Run Go-Fuzz Binary"
          command: |
          make tools & make gofuzz_binary
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  fuzz_test_JSON:
    executor: golang
    steps:
      - run:
          name: "Run Go-Fuzz JSON"
          command: |
          make tools & make gofuzz_json
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"