// +build extensive_tests

// only built if manually enforced
package proto3

import (
	"testing"

	"github.com/golang/protobuf/proto"
	pbf "github.com/golang/protobuf/proto/proto3_proto"
	"github.com/stretchr/testify/assert"
	"github.com/tendermint/go-amino"
	p3 "github.com/tendermint/go-amino/tests/proto3/proto"
)

// This file checks basic proto3 compatibility by checking encoding of some test-vectors generated by using protoc.

func TestEncodeAminoDecodeProto(t *testing.T) {
	cdc := amino.NewCodec()
	type Msg struct {
		Name     string
		Hilarity pbf.Message_Humour
	}
	m := pbf.Message{Name: "Cosmos"}
	ab, err := cdc.MarshalBinaryBare(Msg{Name: "Cosmos"})
	assert.NoError(t, err, "unexpected error")

	pb, err := proto.Marshal(&m)
	assert.NoError(t, err, "unexpected error")
	// This works:
	assert.Equal(t, pb, ab, "encoding doesn't match")

	m = pbf.Message{Name: "Cosmos", Hilarity: pbf.Message_PUNS}
	ab, err = cdc.MarshalBinaryBare(Msg{Name: "Cosmos", Hilarity: pbf.Message_PUNS})
	assert.NoError(t, err, "unexpected error")

	pb, err = proto.Marshal(&m)
	assert.NoError(t, err, "unexpected error")

	m2 := pbf.Nested{Bunny: "foo", Cute: true}
	ab, err = cdc.MarshalBinaryBare(m2)
	assert.NoError(t, err, "unexpected error")

	pb, err = proto.Marshal(&m2)
	assert.NoError(t, err, "unexpected error")
	assert.Equal(t, pb, ab, "encoding doesn't match")

	type testi32 struct {
		Int32 int32 `binary:"fixed32"`
	}
	ab, err = cdc.MarshalBinaryBare(testi32{Int32: 150})
	assert.NoError(t, err, "unexpected error")
	pb, err = proto.Marshal(&p3.Test32{Foo: 150})
	assert.NoError(t, err, "unexpected error")
	assert.Equal(t, pb, ab, "fixed32 (int32) encoding doesn't match")

	type testInt32Varint struct {
		Int32 int `binary:"varint"`
	}
	varint := testInt32Varint{Int32: 150}
	ab, err = cdc.MarshalBinaryBare(varint)
	assert.NoError(t, err, "unexpected error")
	pb, err = proto.Marshal(&p3.TestInt32Varint{Int32: 150})
	assert.NoError(t, err, "unexpected error")
	assert.Equal(t, pb, ab, "varint encoding doesn't match")

	var amToP3 p3.TestInt32Varint
	err = proto.Unmarshal(ab, &amToP3)
	assert.NoError(t, err, "unexpected error")
	assert.Equal(t, varint.Int32, int(amToP3.Int32))
	fixed32 := p3.TestInt32Fixed{Fixed32: 150}
	type TestInt32Fixed struct {
		Fixed32 uint32 `binary:"fixed32"`
	}

	ab, err = cdc.MarshalBinaryBare(TestInt32Fixed{Fixed32: 150})
	assert.NoError(t, err, "unexpected error")
	pb, err = proto.Marshal(&fixed32)
	assert.NoError(t, err, "unexpected error")
	assert.Equal(t, pb, ab, "fixed32 (uint32) encoding doesn't match")

	type test32 struct {
		Foo int32 `binary:"fixed32"`
		Bar int   `binary:"varint"`
	}
	ab, err = cdc.MarshalBinaryBare(test32{Foo: 150, Bar: 150})
	assert.NoError(t, err, "unexpected error")
	pb, err = proto.Marshal(&p3.Test32{Foo: 150, Bar: 150})
	assert.NoError(t, err, "unexpected error")
	assert.Equal(t, pb, ab, "mixed fixed32/varint encoding doesn't match")

	byteMsg := pbf.Message{Data: []byte("hello cosmos")}
	type bm struct {
		Name       string
		Hilarity   pbf.Message_Humour
		HeightInCm uint32
		Data       []byte
	}
	aminoByteMsg := bm{Data: []byte("hello cosmos")}
	ab, err = cdc.MarshalBinaryBare(aminoByteMsg)
	assert.NoError(t, err, "unexpected error")
	pb, err = proto.Marshal(&byteMsg)
	assert.NoError(t, err, "unexpected error")
	assert.Equal(t, pb, ab, "[]byte encoding doesn't match")

	type testUInt64Varint struct {
		Int64 uint64 `binary:"fixed64"`
	}
	varint64 := testUInt64Varint{Int64: 150}
	ab, err = cdc.MarshalBinaryBare(varint64)
	assert.NoError(t, err, "unexpected error")
	pb, err = proto.Marshal(&p3.TestFixedInt64{Int64: 150})
	assert.NoError(t, err, "unexpected error")
	assert.Equal(t, pb, ab, "varint64 encoding doesn't match")
}
