// Code generated by protoc-gen-go. DO NOT EDIT.
// source: compat.proto

package proto3tests

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestInt32Varint struct {
	Int32                int32    `protobuf:"zigzag32,1,opt,name=Int32,proto3" json:"Int32,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestInt32Varint) Reset()         { *m = TestInt32Varint{} }
func (m *TestInt32Varint) String() string { return proto.CompactTextString(m) }
func (*TestInt32Varint) ProtoMessage()    {}
func (*TestInt32Varint) Descriptor() ([]byte, []int) {
	return fileDescriptor_compat_fc5161ab42507406, []int{0}
}
func (m *TestInt32Varint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestInt32Varint.Unmarshal(m, b)
}
func (m *TestInt32Varint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestInt32Varint.Marshal(b, m, deterministic)
}
func (dst *TestInt32Varint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestInt32Varint.Merge(dst, src)
}
func (m *TestInt32Varint) XXX_Size() int {
	return xxx_messageInfo_TestInt32Varint.Size(m)
}
func (m *TestInt32Varint) XXX_DiscardUnknown() {
	xxx_messageInfo_TestInt32Varint.DiscardUnknown(m)
}

var xxx_messageInfo_TestInt32Varint proto.InternalMessageInfo

func (m *TestInt32Varint) GetInt32() int32 {
	if m != nil {
		return m.Int32
	}
	return 0
}

type TestInt32Fixed struct {
	Fixed32              uint32   `protobuf:"fixed32,1,opt,name=Fixed32,proto3" json:"Fixed32,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestInt32Fixed) Reset()         { *m = TestInt32Fixed{} }
func (m *TestInt32Fixed) String() string { return proto.CompactTextString(m) }
func (*TestInt32Fixed) ProtoMessage()    {}
func (*TestInt32Fixed) Descriptor() ([]byte, []int) {
	return fileDescriptor_compat_fc5161ab42507406, []int{1}
}
func (m *TestInt32Fixed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestInt32Fixed.Unmarshal(m, b)
}
func (m *TestInt32Fixed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestInt32Fixed.Marshal(b, m, deterministic)
}
func (dst *TestInt32Fixed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestInt32Fixed.Merge(dst, src)
}
func (m *TestInt32Fixed) XXX_Size() int {
	return xxx_messageInfo_TestInt32Fixed.Size(m)
}
func (m *TestInt32Fixed) XXX_DiscardUnknown() {
	xxx_messageInfo_TestInt32Fixed.DiscardUnknown(m)
}

var xxx_messageInfo_TestInt32Fixed proto.InternalMessageInfo

func (m *TestInt32Fixed) GetFixed32() uint32 {
	if m != nil {
		return m.Fixed32
	}
	return 0
}

type Test32 struct {
	Foo                  uint32   `protobuf:"fixed32,1,opt,name=foo,proto3" json:"foo,omitempty"`
	Bar                  int32    `protobuf:"zigzag32,2,opt,name=bar,proto3" json:"bar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test32) Reset()         { *m = Test32{} }
func (m *Test32) String() string { return proto.CompactTextString(m) }
func (*Test32) ProtoMessage()    {}
func (*Test32) Descriptor() ([]byte, []int) {
	return fileDescriptor_compat_fc5161ab42507406, []int{2}
}
func (m *Test32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test32.Unmarshal(m, b)
}
func (m *Test32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test32.Marshal(b, m, deterministic)
}
func (dst *Test32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test32.Merge(dst, src)
}
func (m *Test32) XXX_Size() int {
	return xxx_messageInfo_Test32.Size(m)
}
func (m *Test32) XXX_DiscardUnknown() {
	xxx_messageInfo_Test32.DiscardUnknown(m)
}

var xxx_messageInfo_Test32 proto.InternalMessageInfo

func (m *Test32) GetFoo() uint32 {
	if m != nil {
		return m.Foo
	}
	return 0
}

func (m *Test32) GetBar() int32 {
	if m != nil {
		return m.Bar
	}
	return 0
}

type TestFixedInt64 struct {
	Int64                uint64   `protobuf:"fixed64,1,opt,name=Int64,proto3" json:"Int64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestFixedInt64) Reset()         { *m = TestFixedInt64{} }
func (m *TestFixedInt64) String() string { return proto.CompactTextString(m) }
func (*TestFixedInt64) ProtoMessage()    {}
func (*TestFixedInt64) Descriptor() ([]byte, []int) {
	return fileDescriptor_compat_fc5161ab42507406, []int{3}
}
func (m *TestFixedInt64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestFixedInt64.Unmarshal(m, b)
}
func (m *TestFixedInt64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestFixedInt64.Marshal(b, m, deterministic)
}
func (dst *TestFixedInt64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestFixedInt64.Merge(dst, src)
}
func (m *TestFixedInt64) XXX_Size() int {
	return xxx_messageInfo_TestFixedInt64.Size(m)
}
func (m *TestFixedInt64) XXX_DiscardUnknown() {
	xxx_messageInfo_TestFixedInt64.DiscardUnknown(m)
}

var xxx_messageInfo_TestFixedInt64 proto.InternalMessageInfo

func (m *TestFixedInt64) GetInt64() uint64 {
	if m != nil {
		return m.Int64
	}
	return 0
}

type TestSFixedSInt64 struct {
	SInt64               int64    `protobuf:"fixed64,1,opt,name=SInt64,proto3" json:"SInt64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestSFixedSInt64) Reset()         { *m = TestSFixedSInt64{} }
func (m *TestSFixedSInt64) String() string { return proto.CompactTextString(m) }
func (*TestSFixedSInt64) ProtoMessage()    {}
func (*TestSFixedSInt64) Descriptor() ([]byte, []int) {
	return fileDescriptor_compat_fc5161ab42507406, []int{4}
}
func (m *TestSFixedSInt64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestSFixedSInt64.Unmarshal(m, b)
}
func (m *TestSFixedSInt64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestSFixedSInt64.Marshal(b, m, deterministic)
}
func (dst *TestSFixedSInt64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestSFixedSInt64.Merge(dst, src)
}
func (m *TestSFixedSInt64) XXX_Size() int {
	return xxx_messageInfo_TestSFixedSInt64.Size(m)
}
func (m *TestSFixedSInt64) XXX_DiscardUnknown() {
	xxx_messageInfo_TestSFixedSInt64.DiscardUnknown(m)
}

var xxx_messageInfo_TestSFixedSInt64 proto.InternalMessageInfo

func (m *TestSFixedSInt64) GetSInt64() int64 {
	if m != nil {
		return m.SInt64
	}
	return 0
}

type EmbeddedStruct struct {
	SomethingFixedLen    int64    `protobuf:"fixed64,1,opt,name=somethingFixedLen,proto3" json:"somethingFixedLen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmbeddedStruct) Reset()         { *m = EmbeddedStruct{} }
func (m *EmbeddedStruct) String() string { return proto.CompactTextString(m) }
func (*EmbeddedStruct) ProtoMessage()    {}
func (*EmbeddedStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_compat_fc5161ab42507406, []int{5}
}
func (m *EmbeddedStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmbeddedStruct.Unmarshal(m, b)
}
func (m *EmbeddedStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmbeddedStruct.Marshal(b, m, deterministic)
}
func (dst *EmbeddedStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbeddedStruct.Merge(dst, src)
}
func (m *EmbeddedStruct) XXX_Size() int {
	return xxx_messageInfo_EmbeddedStruct.Size(m)
}
func (m *EmbeddedStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbeddedStruct.DiscardUnknown(m)
}

var xxx_messageInfo_EmbeddedStruct proto.InternalMessageInfo

func (m *EmbeddedStruct) GetSomethingFixedLen() int64 {
	if m != nil {
		return m.SomethingFixedLen
	}
	return 0
}

type SomeStruct struct {
	// proto3 autom. turns this into a pointer ...
	Emb                  *EmbeddedStruct `protobuf:"bytes,1,opt,name=emb,proto3" json:"emb,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SomeStruct) Reset()         { *m = SomeStruct{} }
func (m *SomeStruct) String() string { return proto.CompactTextString(m) }
func (*SomeStruct) ProtoMessage()    {}
func (*SomeStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_compat_fc5161ab42507406, []int{6}
}
func (m *SomeStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SomeStruct.Unmarshal(m, b)
}
func (m *SomeStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SomeStruct.Marshal(b, m, deterministic)
}
func (dst *SomeStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SomeStruct.Merge(dst, src)
}
func (m *SomeStruct) XXX_Size() int {
	return xxx_messageInfo_SomeStruct.Size(m)
}
func (m *SomeStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_SomeStruct.DiscardUnknown(m)
}

var xxx_messageInfo_SomeStruct proto.InternalMessageInfo

func (m *SomeStruct) GetEmb() *EmbeddedStruct {
	if m != nil {
		return m.Emb
	}
	return nil
}

type ProtoGotTime struct {
	T                    *timestamp.Timestamp `protobuf:"bytes,1,opt,name=T,proto3" json:"T,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProtoGotTime) Reset()         { *m = ProtoGotTime{} }
func (m *ProtoGotTime) String() string { return proto.CompactTextString(m) }
func (*ProtoGotTime) ProtoMessage()    {}
func (*ProtoGotTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_compat_fc5161ab42507406, []int{7}
}
func (m *ProtoGotTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoGotTime.Unmarshal(m, b)
}
func (m *ProtoGotTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoGotTime.Marshal(b, m, deterministic)
}
func (dst *ProtoGotTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoGotTime.Merge(dst, src)
}
func (m *ProtoGotTime) XXX_Size() int {
	return xxx_messageInfo_ProtoGotTime.Size(m)
}
func (m *ProtoGotTime) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoGotTime.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoGotTime proto.InternalMessageInfo

func (m *ProtoGotTime) GetT() *timestamp.Timestamp {
	if m != nil {
		return m.T
	}
	return nil
}

type TestInt32 struct {
	Int32                int32    `protobuf:"varint,1,opt,name=Int32,proto3" json:"Int32,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestInt32) Reset()         { *m = TestInt32{} }
func (m *TestInt32) String() string { return proto.CompactTextString(m) }
func (*TestInt32) ProtoMessage()    {}
func (*TestInt32) Descriptor() ([]byte, []int) {
	return fileDescriptor_compat_fc5161ab42507406, []int{8}
}
func (m *TestInt32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestInt32.Unmarshal(m, b)
}
func (m *TestInt32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestInt32.Marshal(b, m, deterministic)
}
func (dst *TestInt32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestInt32.Merge(dst, src)
}
func (m *TestInt32) XXX_Size() int {
	return xxx_messageInfo_TestInt32.Size(m)
}
func (m *TestInt32) XXX_DiscardUnknown() {
	xxx_messageInfo_TestInt32.DiscardUnknown(m)
}

var xxx_messageInfo_TestInt32 proto.InternalMessageInfo

func (m *TestInt32) GetInt32() int32 {
	if m != nil {
		return m.Int32
	}
	return 0
}

type TestInt64 struct {
	Int64                int64    `protobuf:"varint,1,opt,name=Int64,proto3" json:"Int64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestInt64) Reset()         { *m = TestInt64{} }
func (m *TestInt64) String() string { return proto.CompactTextString(m) }
func (*TestInt64) ProtoMessage()    {}
func (*TestInt64) Descriptor() ([]byte, []int) {
	return fileDescriptor_compat_fc5161ab42507406, []int{9}
}
func (m *TestInt64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestInt64.Unmarshal(m, b)
}
func (m *TestInt64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestInt64.Marshal(b, m, deterministic)
}
func (dst *TestInt64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestInt64.Merge(dst, src)
}
func (m *TestInt64) XXX_Size() int {
	return xxx_messageInfo_TestInt64.Size(m)
}
func (m *TestInt64) XXX_DiscardUnknown() {
	xxx_messageInfo_TestInt64.DiscardUnknown(m)
}

var xxx_messageInfo_TestInt64 proto.InternalMessageInfo

func (m *TestInt64) GetInt64() int64 {
	if m != nil {
		return m.Int64
	}
	return 0
}

func init() {
	proto.RegisterType((*TestInt32Varint)(nil), "proto3tests.TestInt32Varint")
	proto.RegisterType((*TestInt32Fixed)(nil), "proto3tests.TestInt32Fixed")
	proto.RegisterType((*Test32)(nil), "proto3tests.Test32")
	proto.RegisterType((*TestFixedInt64)(nil), "proto3tests.TestFixedInt64")
	proto.RegisterType((*TestSFixedSInt64)(nil), "proto3tests.TestSFixedSInt64")
	proto.RegisterType((*EmbeddedStruct)(nil), "proto3tests.EmbeddedStruct")
	proto.RegisterType((*SomeStruct)(nil), "proto3tests.SomeStruct")
	proto.RegisterType((*ProtoGotTime)(nil), "proto3tests.ProtoGotTime")
	proto.RegisterType((*TestInt32)(nil), "proto3tests.TestInt32")
	proto.RegisterType((*TestInt64)(nil), "proto3tests.TestInt64")
}

func init() { proto.RegisterFile("compat.proto", fileDescriptor_compat_fc5161ab42507406) }

var fileDescriptor_compat_fc5161ab42507406 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x89, 0xa5, 0x29, 0x4e, 0x4b, 0x6d, 0x83, 0x48, 0xa9, 0x07, 0x75, 0x0f, 0x5a, 0x4a,
	0xdd, 0x42, 0x5b, 0x8a, 0x20, 0x78, 0x53, 0x29, 0x78, 0x90, 0x4d, 0xf0, 0x9e, 0x34, 0xd3, 0x1a,
	0x70, 0xb3, 0x21, 0x99, 0x82, 0x1f, 0x5f, 0xf6, 0x4f, 0x5a, 0xab, 0xa7, 0xcc, 0xdb, 0xfd, 0xbd,
	0xc9, 0xf2, 0x1e, 0x74, 0xd6, 0x4a, 0x16, 0x31, 0xf1, 0xa2, 0x54, 0xa4, 0x82, 0xb6, 0xf9, 0xcc,
	0x09, 0x2b, 0xaa, 0x86, 0x57, 0x5b, 0xa5, 0xb6, 0x5f, 0x38, 0x35, 0x67, 0xc9, 0x6e, 0x33, 0xa5,
	0x4c, 0x62, 0x45, 0xb1, 0x2c, 0x2c, 0xcd, 0xee, 0xe0, 0x2c, 0xc2, 0x8a, 0x56, 0x39, 0xcd, 0x67,
	0x1f, 0x71, 0x99, 0xe5, 0x14, 0x9c, 0x43, 0xd3, 0xc8, 0x81, 0x77, 0xed, 0x8d, 0xfa, 0xc2, 0x0a,
	0x36, 0x86, 0xee, 0x1e, 0x7c, 0xc9, 0xbe, 0x31, 0x0d, 0x06, 0xd0, 0x32, 0x83, 0x23, 0x5b, 0xa2,
	0x96, 0x6c, 0x02, 0xbe, 0x66, 0xe7, 0xb3, 0xa0, 0x07, 0x8d, 0x8d, 0x52, 0xee, 0x5e, 0x8f, 0xfa,
	0x24, 0x89, 0xcb, 0xc1, 0x89, 0xd9, 0xad, 0x47, 0x76, 0x6b, 0x37, 0x1b, 0xf3, 0x2a, 0xa7, 0xe5,
	0xc2, 0xbd, 0x60, 0xb9, 0x30, 0x3e, 0x5f, 0x58, 0xc1, 0xc6, 0xd0, 0xd3, 0x5c, 0x68, 0xc0, 0xd0,
	0x92, 0x17, 0xe0, 0x87, 0x07, 0xb4, 0x27, 0x9c, 0x62, 0x4f, 0xd0, 0x7d, 0x96, 0x09, 0xa6, 0x29,
	0xa6, 0x21, 0x95, 0xbb, 0x35, 0x05, 0x13, 0xe8, 0x57, 0x4a, 0x22, 0x7d, 0x66, 0xf9, 0xd6, 0x6c,
	0x78, 0xc3, 0xdc, 0x99, 0xfe, 0x5f, 0xb0, 0x47, 0x80, 0x50, 0x49, 0x74, 0xde, 0x7b, 0x68, 0xa0,
	0x4c, 0x0c, 0xdd, 0x9e, 0x5d, 0xf2, 0x5f, 0x01, 0xf3, 0xe3, 0xbf, 0x08, 0xcd, 0xb1, 0x07, 0xe8,
	0xbc, 0x6b, 0xe4, 0x55, 0x51, 0x94, 0x49, 0x0c, 0x46, 0xe0, 0x45, 0xce, 0x3c, 0xe4, 0xb6, 0x10,
	0x5e, 0x17, 0xc2, 0xa3, 0xba, 0x10, 0xe1, 0x45, 0xec, 0x06, 0x4e, 0xf7, 0x21, 0x1f, 0xf7, 0xd0,
	0xac, 0x7b, 0x38, 0x20, 0x7f, 0x83, 0x6a, 0xb8, 0xa0, 0x12, 0xdf, 0x3e, 0xf0, 0x27, 0x00, 0x00,
	0xff, 0xff, 0x54, 0x43, 0x67, 0xd3, 0x18, 0x02, 0x00, 0x00,
}
