// Code generated by protoc-gen-go. DO NOT EDIT.
// source: compat.proto

package proto3tests

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestInt32Varint struct {
	Int32                int32    `protobuf:"zigzag32,1,opt,name=Int32,proto3" json:"Int32,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestInt32Varint) Reset()         { *m = TestInt32Varint{} }
func (m *TestInt32Varint) String() string { return proto.CompactTextString(m) }
func (*TestInt32Varint) ProtoMessage()    {}
func (*TestInt32Varint) Descriptor() ([]byte, []int) {
	return fileDescriptor_bced3ff93dcaa7f8, []int{0}
}

func (m *TestInt32Varint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestInt32Varint.Unmarshal(m, b)
}
func (m *TestInt32Varint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestInt32Varint.Marshal(b, m, deterministic)
}
func (m *TestInt32Varint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestInt32Varint.Merge(m, src)
}
func (m *TestInt32Varint) XXX_Size() int {
	return xxx_messageInfo_TestInt32Varint.Size(m)
}
func (m *TestInt32Varint) XXX_DiscardUnknown() {
	xxx_messageInfo_TestInt32Varint.DiscardUnknown(m)
}

var xxx_messageInfo_TestInt32Varint proto.InternalMessageInfo

func (m *TestInt32Varint) GetInt32() int32 {
	if m != nil {
		return m.Int32
	}
	return 0
}

type TestInt32Fixed struct {
	Fixed32              uint32   `protobuf:"fixed32,1,opt,name=Fixed32,proto3" json:"Fixed32,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestInt32Fixed) Reset()         { *m = TestInt32Fixed{} }
func (m *TestInt32Fixed) String() string { return proto.CompactTextString(m) }
func (*TestInt32Fixed) ProtoMessage()    {}
func (*TestInt32Fixed) Descriptor() ([]byte, []int) {
	return fileDescriptor_bced3ff93dcaa7f8, []int{1}
}

func (m *TestInt32Fixed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestInt32Fixed.Unmarshal(m, b)
}
func (m *TestInt32Fixed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestInt32Fixed.Marshal(b, m, deterministic)
}
func (m *TestInt32Fixed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestInt32Fixed.Merge(m, src)
}
func (m *TestInt32Fixed) XXX_Size() int {
	return xxx_messageInfo_TestInt32Fixed.Size(m)
}
func (m *TestInt32Fixed) XXX_DiscardUnknown() {
	xxx_messageInfo_TestInt32Fixed.DiscardUnknown(m)
}

var xxx_messageInfo_TestInt32Fixed proto.InternalMessageInfo

func (m *TestInt32Fixed) GetFixed32() uint32 {
	if m != nil {
		return m.Fixed32
	}
	return 0
}

type Test32 struct {
	Foo                  uint32   `protobuf:"fixed32,1,opt,name=foo,proto3" json:"foo,omitempty"`
	Bar                  int32    `protobuf:"zigzag32,2,opt,name=bar,proto3" json:"bar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test32) Reset()         { *m = Test32{} }
func (m *Test32) String() string { return proto.CompactTextString(m) }
func (*Test32) ProtoMessage()    {}
func (*Test32) Descriptor() ([]byte, []int) {
	return fileDescriptor_bced3ff93dcaa7f8, []int{2}
}

func (m *Test32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test32.Unmarshal(m, b)
}
func (m *Test32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test32.Marshal(b, m, deterministic)
}
func (m *Test32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test32.Merge(m, src)
}
func (m *Test32) XXX_Size() int {
	return xxx_messageInfo_Test32.Size(m)
}
func (m *Test32) XXX_DiscardUnknown() {
	xxx_messageInfo_Test32.DiscardUnknown(m)
}

var xxx_messageInfo_Test32 proto.InternalMessageInfo

func (m *Test32) GetFoo() uint32 {
	if m != nil {
		return m.Foo
	}
	return 0
}

func (m *Test32) GetBar() int32 {
	if m != nil {
		return m.Bar
	}
	return 0
}

type TestFixedInt64 struct {
	Int64                uint64   `protobuf:"fixed64,1,opt,name=Int64,proto3" json:"Int64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestFixedInt64) Reset()         { *m = TestFixedInt64{} }
func (m *TestFixedInt64) String() string { return proto.CompactTextString(m) }
func (*TestFixedInt64) ProtoMessage()    {}
func (*TestFixedInt64) Descriptor() ([]byte, []int) {
	return fileDescriptor_bced3ff93dcaa7f8, []int{3}
}

func (m *TestFixedInt64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestFixedInt64.Unmarshal(m, b)
}
func (m *TestFixedInt64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestFixedInt64.Marshal(b, m, deterministic)
}
func (m *TestFixedInt64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestFixedInt64.Merge(m, src)
}
func (m *TestFixedInt64) XXX_Size() int {
	return xxx_messageInfo_TestFixedInt64.Size(m)
}
func (m *TestFixedInt64) XXX_DiscardUnknown() {
	xxx_messageInfo_TestFixedInt64.DiscardUnknown(m)
}

var xxx_messageInfo_TestFixedInt64 proto.InternalMessageInfo

func (m *TestFixedInt64) GetInt64() uint64 {
	if m != nil {
		return m.Int64
	}
	return 0
}

type TestSFixedSInt64 struct {
	SInt64               int64    `protobuf:"fixed64,1,opt,name=SInt64,proto3" json:"SInt64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestSFixedSInt64) Reset()         { *m = TestSFixedSInt64{} }
func (m *TestSFixedSInt64) String() string { return proto.CompactTextString(m) }
func (*TestSFixedSInt64) ProtoMessage()    {}
func (*TestSFixedSInt64) Descriptor() ([]byte, []int) {
	return fileDescriptor_bced3ff93dcaa7f8, []int{4}
}

func (m *TestSFixedSInt64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestSFixedSInt64.Unmarshal(m, b)
}
func (m *TestSFixedSInt64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestSFixedSInt64.Marshal(b, m, deterministic)
}
func (m *TestSFixedSInt64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestSFixedSInt64.Merge(m, src)
}
func (m *TestSFixedSInt64) XXX_Size() int {
	return xxx_messageInfo_TestSFixedSInt64.Size(m)
}
func (m *TestSFixedSInt64) XXX_DiscardUnknown() {
	xxx_messageInfo_TestSFixedSInt64.DiscardUnknown(m)
}

var xxx_messageInfo_TestSFixedSInt64 proto.InternalMessageInfo

func (m *TestSFixedSInt64) GetSInt64() int64 {
	if m != nil {
		return m.SInt64
	}
	return 0
}

type EmbeddedStruct struct {
	SomethingFixedLen    int64    `protobuf:"fixed64,1,opt,name=somethingFixedLen,proto3" json:"somethingFixedLen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmbeddedStruct) Reset()         { *m = EmbeddedStruct{} }
func (m *EmbeddedStruct) String() string { return proto.CompactTextString(m) }
func (*EmbeddedStruct) ProtoMessage()    {}
func (*EmbeddedStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_bced3ff93dcaa7f8, []int{5}
}

func (m *EmbeddedStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmbeddedStruct.Unmarshal(m, b)
}
func (m *EmbeddedStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmbeddedStruct.Marshal(b, m, deterministic)
}
func (m *EmbeddedStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbeddedStruct.Merge(m, src)
}
func (m *EmbeddedStruct) XXX_Size() int {
	return xxx_messageInfo_EmbeddedStruct.Size(m)
}
func (m *EmbeddedStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbeddedStruct.DiscardUnknown(m)
}

var xxx_messageInfo_EmbeddedStruct proto.InternalMessageInfo

func (m *EmbeddedStruct) GetSomethingFixedLen() int64 {
	if m != nil {
		return m.SomethingFixedLen
	}
	return 0
}

type SomeStruct struct {
	// proto3 autom. turns this into a pointer ...
	Emb                  *EmbeddedStruct `protobuf:"bytes,1,opt,name=emb,proto3" json:"emb,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SomeStruct) Reset()         { *m = SomeStruct{} }
func (m *SomeStruct) String() string { return proto.CompactTextString(m) }
func (*SomeStruct) ProtoMessage()    {}
func (*SomeStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_bced3ff93dcaa7f8, []int{6}
}

func (m *SomeStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SomeStruct.Unmarshal(m, b)
}
func (m *SomeStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SomeStruct.Marshal(b, m, deterministic)
}
func (m *SomeStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SomeStruct.Merge(m, src)
}
func (m *SomeStruct) XXX_Size() int {
	return xxx_messageInfo_SomeStruct.Size(m)
}
func (m *SomeStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_SomeStruct.DiscardUnknown(m)
}

var xxx_messageInfo_SomeStruct proto.InternalMessageInfo

func (m *SomeStruct) GetEmb() *EmbeddedStruct {
	if m != nil {
		return m.Emb
	}
	return nil
}

type ProtoGotTime struct {
	T                    *timestamp.Timestamp `protobuf:"bytes,1,opt,name=T,proto3" json:"T,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProtoGotTime) Reset()         { *m = ProtoGotTime{} }
func (m *ProtoGotTime) String() string { return proto.CompactTextString(m) }
func (*ProtoGotTime) ProtoMessage()    {}
func (*ProtoGotTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_bced3ff93dcaa7f8, []int{7}
}

func (m *ProtoGotTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoGotTime.Unmarshal(m, b)
}
func (m *ProtoGotTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoGotTime.Marshal(b, m, deterministic)
}
func (m *ProtoGotTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoGotTime.Merge(m, src)
}
func (m *ProtoGotTime) XXX_Size() int {
	return xxx_messageInfo_ProtoGotTime.Size(m)
}
func (m *ProtoGotTime) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoGotTime.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoGotTime proto.InternalMessageInfo

func (m *ProtoGotTime) GetT() *timestamp.Timestamp {
	if m != nil {
		return m.T
	}
	return nil
}

type TestInt32 struct {
	Int32                int32    `protobuf:"varint,1,opt,name=Int32,proto3" json:"Int32,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestInt32) Reset()         { *m = TestInt32{} }
func (m *TestInt32) String() string { return proto.CompactTextString(m) }
func (*TestInt32) ProtoMessage()    {}
func (*TestInt32) Descriptor() ([]byte, []int) {
	return fileDescriptor_bced3ff93dcaa7f8, []int{8}
}

func (m *TestInt32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestInt32.Unmarshal(m, b)
}
func (m *TestInt32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestInt32.Marshal(b, m, deterministic)
}
func (m *TestInt32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestInt32.Merge(m, src)
}
func (m *TestInt32) XXX_Size() int {
	return xxx_messageInfo_TestInt32.Size(m)
}
func (m *TestInt32) XXX_DiscardUnknown() {
	xxx_messageInfo_TestInt32.DiscardUnknown(m)
}

var xxx_messageInfo_TestInt32 proto.InternalMessageInfo

func (m *TestInt32) GetInt32() int32 {
	if m != nil {
		return m.Int32
	}
	return 0
}

type TestInts struct {
	Int32                int32    `protobuf:"varint,1,opt,name=Int32,proto3" json:"Int32,omitempty"`
	Int64                int64    `protobuf:"varint,2,opt,name=Int64,proto3" json:"Int64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestInts) Reset()         { *m = TestInts{} }
func (m *TestInts) String() string { return proto.CompactTextString(m) }
func (*TestInts) ProtoMessage()    {}
func (*TestInts) Descriptor() ([]byte, []int) {
	return fileDescriptor_bced3ff93dcaa7f8, []int{9}
}

func (m *TestInts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestInts.Unmarshal(m, b)
}
func (m *TestInts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestInts.Marshal(b, m, deterministic)
}
func (m *TestInts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestInts.Merge(m, src)
}
func (m *TestInts) XXX_Size() int {
	return xxx_messageInfo_TestInts.Size(m)
}
func (m *TestInts) XXX_DiscardUnknown() {
	xxx_messageInfo_TestInts.DiscardUnknown(m)
}

var xxx_messageInfo_TestInts proto.InternalMessageInfo

func (m *TestInts) GetInt32() int32 {
	if m != nil {
		return m.Int32
	}
	return 0
}

func (m *TestInts) GetInt64() int64 {
	if m != nil {
		return m.Int64
	}
	return 0
}

type TypeDefIntTestVec struct {
	Val                  int64    `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypeDefIntTestVec) Reset()         { *m = TypeDefIntTestVec{} }
func (m *TypeDefIntTestVec) String() string { return proto.CompactTextString(m) }
func (*TypeDefIntTestVec) ProtoMessage()    {}
func (*TypeDefIntTestVec) Descriptor() ([]byte, []int) {
	return fileDescriptor_bced3ff93dcaa7f8, []int{10}
}

func (m *TypeDefIntTestVec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeDefIntTestVec.Unmarshal(m, b)
}
func (m *TypeDefIntTestVec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeDefIntTestVec.Marshal(b, m, deterministic)
}
func (m *TypeDefIntTestVec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeDefIntTestVec.Merge(m, src)
}
func (m *TypeDefIntTestVec) XXX_Size() int {
	return xxx_messageInfo_TypeDefIntTestVec.Size(m)
}
func (m *TypeDefIntTestVec) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeDefIntTestVec.DiscardUnknown(m)
}

var xxx_messageInfo_TypeDefIntTestVec proto.InternalMessageInfo

func (m *TypeDefIntTestVec) GetVal() int64 {
	if m != nil {
		return m.Val
	}
	return 0
}

type TypeDefIntArr struct {
	Val                  []int64  `protobuf:"varint,1,rep,packed,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypeDefIntArr) Reset()         { *m = TypeDefIntArr{} }
func (m *TypeDefIntArr) String() string { return proto.CompactTextString(m) }
func (*TypeDefIntArr) ProtoMessage()    {}
func (*TypeDefIntArr) Descriptor() ([]byte, []int) {
	return fileDescriptor_bced3ff93dcaa7f8, []int{11}
}

func (m *TypeDefIntArr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeDefIntArr.Unmarshal(m, b)
}
func (m *TypeDefIntArr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeDefIntArr.Marshal(b, m, deterministic)
}
func (m *TypeDefIntArr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeDefIntArr.Merge(m, src)
}
func (m *TypeDefIntArr) XXX_Size() int {
	return xxx_messageInfo_TypeDefIntArr.Size(m)
}
func (m *TypeDefIntArr) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeDefIntArr.DiscardUnknown(m)
}

var xxx_messageInfo_TypeDefIntArr proto.InternalMessageInfo

func (m *TypeDefIntArr) GetVal() []int64 {
	if m != nil {
		return m.Val
	}
	return nil
}

func init() {
	proto.RegisterType((*TestInt32Varint)(nil), "proto3tests.TestInt32Varint")
	proto.RegisterType((*TestInt32Fixed)(nil), "proto3tests.TestInt32Fixed")
	proto.RegisterType((*Test32)(nil), "proto3tests.Test32")
	proto.RegisterType((*TestFixedInt64)(nil), "proto3tests.TestFixedInt64")
	proto.RegisterType((*TestSFixedSInt64)(nil), "proto3tests.TestSFixedSInt64")
	proto.RegisterType((*EmbeddedStruct)(nil), "proto3tests.EmbeddedStruct")
	proto.RegisterType((*SomeStruct)(nil), "proto3tests.SomeStruct")
	proto.RegisterType((*ProtoGotTime)(nil), "proto3tests.ProtoGotTime")
	proto.RegisterType((*TestInt32)(nil), "proto3tests.TestInt32")
	proto.RegisterType((*TestInts)(nil), "proto3tests.TestInts")
	proto.RegisterType((*TypeDefIntTestVec)(nil), "proto3tests.TypeDefIntTestVec")
	proto.RegisterType((*TypeDefIntArr)(nil), "proto3tests.TypeDefIntArr")
}

func init() { proto.RegisterFile("compat.proto", fileDescriptor_bced3ff93dcaa7f8) }

var fileDescriptor_bced3ff93dcaa7f8 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x5f, 0x6b, 0xea, 0x40,
	0x10, 0xc5, 0xc9, 0x0d, 0xc6, 0x7b, 0x47, 0xaf, 0xd5, 0x50, 0x8a, 0xd8, 0x87, 0xd6, 0x85, 0xb6,
	0x22, 0x36, 0x82, 0x8a, 0x14, 0x0a, 0x85, 0x42, 0xff, 0x20, 0xf4, 0xa1, 0x24, 0xc1, 0xf7, 0xc4,
	0x8c, 0x36, 0xe0, 0x66, 0x43, 0x32, 0x96, 0xf6, 0xdb, 0x97, 0xdd, 0x6c, 0x4c, 0xa5, 0x7d, 0xca,
	0x9c, 0xdd, 0xdf, 0x99, 0x24, 0xe7, 0x40, 0x73, 0x25, 0x78, 0x1a, 0x90, 0x93, 0x66, 0x82, 0x84,
	0xdd, 0x50, 0x8f, 0x29, 0x61, 0x4e, 0x79, 0xef, 0x6c, 0x23, 0xc4, 0x66, 0x8b, 0x63, 0x75, 0x16,
	0xee, 0xd6, 0x63, 0x8a, 0x39, 0xe6, 0x14, 0xf0, 0xb4, 0xa0, 0xd9, 0x15, 0x1c, 0xf9, 0x98, 0xd3,
	0x22, 0xa1, 0xe9, 0x64, 0x19, 0x64, 0x71, 0x42, 0xf6, 0x31, 0xd4, 0x94, 0xec, 0x1a, 0xe7, 0xc6,
	0xa0, 0xe3, 0x16, 0x82, 0x0d, 0xa1, 0xb5, 0x07, 0x9f, 0xe2, 0x0f, 0x8c, 0xec, 0x2e, 0xd4, 0xd5,
	0xa0, 0xc9, 0xba, 0x5b, 0x4a, 0x36, 0x02, 0x4b, 0xb2, 0xd3, 0x89, 0xdd, 0x06, 0x73, 0x2d, 0x84,
	0xbe, 0x97, 0xa3, 0x3c, 0x09, 0x83, 0xac, 0xfb, 0x47, 0xed, 0x96, 0x23, 0xbb, 0x2c, 0x36, 0x2b,
	0xf3, 0x22, 0xa1, 0xf9, 0x4c, 0x7f, 0xc1, 0x7c, 0xa6, 0x7c, 0x96, 0x5b, 0x08, 0x36, 0x84, 0xb6,
	0xe4, 0x3c, 0x05, 0x7a, 0x05, 0x79, 0x02, 0x96, 0x57, 0xa1, 0x6d, 0x57, 0x2b, 0x76, 0x07, 0xad,
	0x47, 0x1e, 0x62, 0x14, 0x61, 0xe4, 0x51, 0xb6, 0x5b, 0x91, 0x3d, 0x82, 0x4e, 0x2e, 0x38, 0xd2,
	0x5b, 0x9c, 0x6c, 0xd4, 0x86, 0x17, 0x4c, 0xb4, 0xe9, 0xe7, 0x05, 0xbb, 0x05, 0xf0, 0x04, 0x47,
	0xed, 0xbd, 0x06, 0x13, 0x79, 0xa8, 0xe8, 0xc6, 0xe4, 0xd4, 0xf9, 0x16, 0xb0, 0x73, 0xf8, 0x16,
	0x57, 0x72, 0xec, 0x06, 0x9a, 0xaf, 0x12, 0x79, 0x16, 0xe4, 0xc7, 0x1c, 0xed, 0x01, 0x18, 0xbe,
	0x36, 0xf7, 0x9c, 0xa2, 0x10, 0xa7, 0x2c, 0xc4, 0xf1, 0xcb, 0x42, 0x5c, 0xc3, 0x67, 0x7d, 0xf8,
	0xb7, 0x0f, 0xf9, 0xb0, 0x87, 0x5a, 0xd9, 0xc3, 0x1c, 0xfe, 0x6a, 0x24, 0xff, 0x9d, 0xa8, 0xd2,
	0x93, 0x19, 0x9b, 0x65, 0x7a, 0x17, 0xd0, 0xf1, 0x3f, 0x53, 0x7c, 0xc0, 0xf5, 0x22, 0x21, 0xb9,
	0x61, 0x89, 0x2b, 0x59, 0xc6, 0x7b, 0xb0, 0x55, 0x76, 0xd3, 0x95, 0x23, 0xeb, 0xc3, 0xff, 0x0a,
	0xbb, 0xcf, 0xb2, 0x0a, 0x31, 0x35, 0x12, 0x5a, 0xc5, 0xff, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff,
	0xc7, 0xe2, 0xc4, 0x4d, 0x77, 0x02, 0x00, 0x00,
}
